// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyhRDZNxP8H_LYTKJoAzRkxRLDVvgUJqM',
    appId: '1:225218873891:web:979917413edd06b508ff96',
    messagingSenderId: '225218873891',
    projectId: 'qiyasready',
    authDomain: 'qiyasready.firebaseapp.com',
    storageBucket: 'qiyasready.firebasestorage.app',
    measurementId: 'G-F8BTQGQ83D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1a0xIiDC0nNlQDvimXlXVLPZPi2bWD2w',
    appId: '1:225218873891:android:c3baa2ce2a1fba9408ff96',
    messagingSenderId: '225218873891',
    projectId: 'qiyasready',
    storageBucket: 'qiyasready.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnZmFABwm_OFtgb8W36ghr_CtKwEWzIE',
    appId: '1:225218873891:ios:16e7a7699058929708ff96',
    messagingSenderId: '225218873891',
    projectId: 'qiyasready',
    storageBucket: 'qiyasready.firebasestorage.app',
    iosBundleId: 'com.qiyasready.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyhRDZNxP8H_LYTKJoAzRkxRLDVvgUJqM',
    appId: '1:225218873891:web:8a5d2d7950524d6d08ff96',
    messagingSenderId: '225218873891',
    projectId: 'qiyasready',
    authDomain: 'qiyasready.firebaseapp.com',
    storageBucket: 'qiyasready.firebasestorage.app',
    measurementId: 'G-H9QM9SKDR4',
  );
}
